import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ApolloClientProvider from '@/context/ApolloClientProvider'
import DndReactProvider from '@/context/DndReactProvider'
import { Navbar } from '@/common/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mini trello',
  description: 'Generated by Joao Gustavo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <ApolloClientProvider>
            <Navbar />

            <DndReactProvider>{children}</DndReactProvider>
          </ApolloClientProvider>
        </div>
      </body>
    </html>
  )
}
